name = input("Hi, Whats your name?").strip().title()
city=input("Where are you from?").strip().title()
birth_year= int(input("whats your YOB"))
print("="*30)
print(" "*7, "PROFILE CARD")
print("="*30)
print(f"Name   :{name}")
print(f"City   :{city}")
print(f"Age    :{2026-birth_year}")
print(f"Letters in name :{len(name)}")